// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqAN2ynynmIPpTQcpmxFzEdE66vFvINQ',
    appId: '1:843594121052:web:fe594ca7acaa1857fc8b99',
    messagingSenderId: '843594121052',
    projectId: 'plantsdoctor2023',
    authDomain: 'plantsdoctor2023.firebaseapp.com',
    databaseURL: 'https://plantsdoctor2023-default-rtdb.firebaseio.com',
    storageBucket: 'plantsdoctor2023.appspot.com',
    measurementId: 'G-7QBVQRMCDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVz3jrrzdYbl1S103s1yHEw0IjkSwT74A',
    appId: '1:843594121052:android:00b5b13f7c1354e7fc8b99',
    messagingSenderId: '843594121052',
    projectId: 'plantsdoctor2023',
    databaseURL: 'https://plantsdoctor2023-default-rtdb.firebaseio.com',
    storageBucket: 'plantsdoctor2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4YABCRkI10F6Y5dwd2919qY7ogPbnBRU',
    appId: '1:843594121052:ios:612c0c22f9bb63bafc8b99',
    messagingSenderId: '843594121052',
    projectId: 'plantsdoctor2023',
    databaseURL: 'https://plantsdoctor2023-default-rtdb.firebaseio.com',
    storageBucket: 'plantsdoctor2023.appspot.com',
    iosBundleId: 'com.ahmednasser1601.plantsDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4YABCRkI10F6Y5dwd2919qY7ogPbnBRU',
    appId: '1:843594121052:ios:612c0c22f9bb63bafc8b99',
    messagingSenderId: '843594121052',
    projectId: 'plantsdoctor2023',
    databaseURL: 'https://plantsdoctor2023-default-rtdb.firebaseio.com',
    storageBucket: 'plantsdoctor2023.appspot.com',
    iosBundleId: 'com.ahmednasser1601.plantsDoctor',
  );
}
